- README.md
- models.py
- reamp.py
- requirements.txt
- train.py
Reverts sdatkinson/neural-amp-modeler#2
> Revert "PyTorch"

- bin/train/main.py
- nam/data.py
- nam/models/_base.py
- nam/models/base.py
- nam/models/hyper_net.py
- tests/test_nam/test_data.py
Closes #23 with a parametric model implemented using a hypernet
> Parametric model

- nam/models/hyper_net.py
- tests/test_nam/test_models/base.py
- tests/test_nam/test_models/test_conv_net.py
- tests/test_nam/test_models/test_hyper_net.py
Closes #27. 
Fill in missing export code.
> Exporting Hypernet models

- bin/train/easy_colab.ipynb
- nam/train/colab.py
> New input signal for easy_colab.ipynb

- bin/train/easy_colab.ipynb
> Add TensorBoard monitoring to easy_colab.ipynb

- nam/train/colab.py
> Expose head_scale as a settable parameter, default to 0.02

- nam/__init__.py
- nam/util.py
> Utility module

- bin/train/inputs/learning/default.json
- bin/train/inputs/models/wavenet.json
Resolves #76.
Keep up with easy mode ;)
> Update training input defaults

- bin/train/easy_colab.ipynb
- nam/train/colab.py
> Add different pre-made architectures to easy mode

- nam/data.py
- tests/test_nam/test_data.py
> Non-integer delays

- bin/export/main.py
- environment_cpu.yml
- environment_gpu.yml
- nam/models/_exportable.py
- nam/models/recurrent.py
- requirements.txt
- tests/test_nam/test_models/test_recurrent.py
> ONNX support for LSTMs

- nam/train/colab.py
> Export model indices start at zero

- nam/data.py
> Add rate param to wav_to_np

- nam/_core.py
- nam/data.py
- nam/train/core.py
Resolves #123
* Better explanation when input & output have different lengths or number of channels
* Better error messages and plotting diagnostics when delay calibration doesn't work as expected.
> Better error messages

- nam/models/base.py
Adding experimental multiresolution STFT loss from auraloss package in addition to the normal loss, antialias seems to be reduced based on the experiments here: https://github.com/honkkis/neural-amp-modeler/blob/WIP_stft_loss/dev/stft/stft_tests1.png , where top is the target, middle is with the MRSTFT loss, and bottom is the normal loss.
> Added experimental multiresolution STFT loss using auraloss.

- environment_cpu.yml
- environment_gpu.yml
- nam/models/base.py
- requirements.txt
- setup.py
- tests/test_nam/test_models/test_base.py
Added to environment and package specs
Added tests
Resolves #152
> Auraloss dependency

- nam/models/recurrent.py
> fix typo in recurrent.py

- nam/train/core.py
- nam/train/gui.py
QOL changes and some info I probably should have included in the first PR :)
Change button info string to be more helpful, add digit to ESR
- Make GUI text a bit more helpful by adding more information for buttons/controls and clarifying multi select for batch
- Increase displayed significant digits on ESR plot and console output because many results now reaching < 0.001 and display 0.000 which is confusing.
Use the info_str attribute for this purpose and use button label instead to indicate when a button is set
-- Same as current when selected -- 
https://user-images.githubusercontent.com/44332958/230697376-a13213d8-8d9a-4b26-9d5c-49e0ee1b8784.mp4
> Change button info string to be more helpful, add digit to ESR

- environment_cpu.yml
- environment_gpu.yml
- nam/models/_base.py
- nam/models/_exportable.py
- nam/models/losses.py
- nam/models/metadata.py
- nam/train/gui.py
- requirements.txt
- setup.py
- tests/test_nam/test_models/test_base.py
- tests/test_nam/test_models/test_exportable.py
First part of #176: get metadata in the GUI trainer
> Metadata in GUI trainer

- nam/train/core.py
> Colab: Ensure model is on CPU before plotting prediction vs target

- nam/train/core.py
There's no reason for this at all
But heck
> I'm all out of bubblegum

- nam/train/core.py
Resolves #124
Implements "weak" matching along with the existing "strong" matching tor recognize input audio files. Strong requires a full hash match on the file; weak only requires matching the parts that matter (the start for alignment and such; the end for validation)
> Strong and weak matches for recognized training files

- bin/export/main.py
- bin/train/inputs/data/single_pair.json
- bin/train/inputs/data/two_pairs.json
- bin/train/inputs/learning/default.json
- bin/train/inputs/learning/demo.json
- bin/train/inputs/models/catlstm.json
- bin/train/inputs/models/convnet.json
- bin/train/inputs/models/demonet.json
- bin/train/inputs/models/lstm.json
- bin/train/inputs/models/wavenet.json
- bin/train/main.py
- tests/test_bin/test_train/test_main.py
Resolves #223 on `bin/train/main.py` and `bin/export/main.py`
Add end-to-end tests of the former.
> Fix model device handling

- nam/train/colab.py
> Fix broken enumeration

- nam/models/_exportable.py
- nam/models/wavenet.py
- tests/test_nam/test_models/test_wavenet.py
> Importing weights for WaveNet

- nam/data.py
- tests/test_nam/test_data.py
> Fix AudioShapeMismatchError mixed up arguments

- nam/models/_base.py
- nam/models/recurrent.py
- tests/test_nam/test_models/test_recurrent.py
Exposes a few things and mocks them with lighter alternatives.
Resolves #273
> Faster recurrent testing with shorter inputs

- bin/train/easy_colab.ipynb
Related to #282. Need change to README.md to resolve Issue.
> Add `ignore_checks` kwarg explicitly to help users see what to change

- bin/train/main.py
- nam/models/_base.py
- nam/train/core.py
- tests/resources/__init__.py
- tests/test_nam/test_train/test_core.py
Implements warning suggested in #304.
Also some other odds & ends :)
> Warn if calibrated delay is the maximum lookahead

- bin/train/easy_colab.ipynb
- nam/models/metadata.py
> Add pedal_amp to GearType enum

- .github/workflows/python-package.yml
> [Chore] Add workflow_dispatch option for build action

- nam/models/base.py
> [Enhancement] Extensible registry of `BaseNet` subclass constructors

- environment_cpu.yml
- environment_gpu.yml
- requirements.txt
Version-block `onnxruntime`
Resolves #312
> Fix the build

- bin/train/main.py
> Report ESR instead of NRMSE in CLI trainer

- environment_cpu.yml
- environment_gpu.yml
- requirements.txt
> Update environment specs

- nam/train/core.py
- tests/test_nam/test_train/test_core.py
> [BUGFIX] Silent mode for V3

- nam/data.py
- tests/test_nam/test_data.py
> [FEATURE] Dataset class registry

- README.md
- environment_gpu.yml
> Update PyTorch CUDA version to 12.1

- bin/train/main.py
- nam/train/core.py
- nam/util.py
This includes the infamous "num_workers" warning, which is a false positive.
Resolves #345
> Ignore PyTorch Lightning `PossibleUserWarning`s during `trainer.fit()`

- nam/models/_exportable.py
> Pydantic updates

- nam/data.py
- tests/test_nam/test_data.py
> [FEATURE] start and stop trimming for datasets in seconds instead of samples

- nam/train/core.py
- tests/resources/__init__.py
- tests/test_nam/test_train/test_core.py
> [FEATURE] Add support for Proteus training files

- docs/source/tutorials/gui.rst
Someone asked about batch training, so I thought something could be written about it. Feel free to amend to your liking.
> Document how to do batch training

- nam/train/gui.py
Darker red
Clearer about batch mode
Resolves #388
> [ENHANCEMENT] Improve GUI text

- nam/train/_names.py
- nam/train/gui.py
> [ENHANCEMENT] GUI: Button to download the training input audio file

- nam/train/core.py
- nam/train/gui.py
> Get user metadata in checkpoint .nams

- nam/train/gui.py
> GUI: Re-enable main window correctly when closing secondary windows

- .github/workflows/python-package.yml
> [TESTING] Add Python 3.11 and 3.12 to the workflow matrix

- nam/train/metadata.py
> [BUG] disagreement metatdata is int instead of bool (#432)

- nam/models/exportable.py
> Bump .nam file patch version

- docs/source/index.rst
- docs/source/model-file.rst
> Documentation on the `.nam` file format

- nam/train/gui/__init__.py
- tests/test_nam/test_train/test_gui.py
> Extensions

- nam/train/gui/__init__.py
- tests/test_nam/test_train/test_gui.py
> [BUGFIX] Correct OS environment variable for home directory on Windows

- nam/data.py
- nam/models/recurrent.py
- tests/test_nam/test_models/test_recurrent.py
Resolves #450 
Also fixes a few bugs that seem to have creeped in with the LSTM when using GPU.
> [BUGFIX] Fix LSTM cuDNN bug for PyTorch 2.4

- nam/train/_names.py
- nam/train/_version.py
- nam/train/colab.py
- nam/train/gui/__init__.py
Resolves #443.
Tested the GUI and Colab trainer by hand to make sure they behave as expected.
> Rename `v3_0_0.wav` to `input.wav`

- nam/train/colab.py
- nam/train/core.py
- nam/train/gui/__init__.py
- nam/train/metadata.py
> [BREAKING] Remove cab-fitting checkbox from GUI trainer

- nam/train/core.py
- nam/train/gui/__init__.py
- tests/test_nam/test_models/test_wavenet.py
* `nam.train.core.get_lstm_config`
* `nam.train.core.get_wavenet_config`
* `nam.train.gui.GUI.core_train_kwargs`
* `nam.train.gui.LabeledOptionMenu`
* `nam.train.gui.LabeledText`
To make it easier to make some extensions that use them.
> Make some attributes public

- nam/data.py
- nam/train/core.py
- nam/train/gui/__init__.py
Resolves #473 
I've also put in some things to anticipate allowing different-length audio files, but that will need more work in the data loading.
> Data validation: Check audio length and sample rates for matches

- docs/source/installation.rst
update pytorch-cuda version to match https://github.com/sdatkinson/neural-amp-modeler/pull/342
> update pytorch-cuda version

- nam/train/gui/__init__.py
> [BUGFIX] Handle no IDLE support

- docs/source/installation.rst
> Update install instructions to Miniconda

- .github/workflows/python-package.yml
- environments/environment_cpu_apple.yml
- environments/environment_gpu.yml
- nam/cli.py
- nam/data.py
- nam/models/recurrent.py
- pyproject.toml
- tests/test_nam/test_data.py
- tests/test_nam/test_models/test_base.py
Also removes scipy dependency.
Resolves #539.
> [BREAKING] Remove support for non-integer latency compensation

- .github/workflows/python-package.yml
> added python 3.13 support

- nam/models/base.py
> Remove deprecated use of pkg_resources

- nam/cli.py
> [FEATURE] Add `--no-plots` flag to `nam-full`

- nam/models/__init__.py
- nam/models/_from_nam.py
- nam/models/wavenet.py
- tests/test_nam/test_models/test_from_nam.py
Related to #233, but doesn't resolve--we still need the other architectures!
> [FEATURE] Implement loading WaveNet model from .nam file

- environments/environment_cpu_apple.yml
- environments/environment_gpu.yml
- nam/train/colab.py
- nam/train/core.py
- pyproject.toml
Resolves #503
Note to future self: I'm also lifting the numpy<2 constraint int hsi PR. This is risky but I think that PyTorch is ready. If I'm wrong, then blame current self.
> [BUGFIX] Detect input versions correctly in Colab

- nam/models/_abc.py
- nam/models/_from_nam.py
- nam/models/exportable.py
- nam/models/linear.py
- nam/models/recurrent.py
- nam/models/wavenet.py
- tests/test_nam/test_models/test_from_nam.py
Resolves #233 (meh, I can do without ConvNet 🙂)
> [FEATURE] init_from_nam for LSTM and Linear architectures

- nam/_core.py
- nam/data.py
- nam/train/core.py
- nam/train/full.py
> [FEAUTRE] `.teardown()` method for datasets

- README.md
https://www.neuralampmodeler.com/ has plenty of great info about the ecosystem, I didn't understand the input/process/output with the documentation in this repo but the website explains it very well :)
> Add a pointer to the main website
