sdatkinson/neural-amp-modeler

nam/data.py, tests/test_nam/test_data.py
When instantiating `nam.data.Dataset`, validate `x`, `y`, `start`, and `stop` with better error messages.
Resolves #14 and #96
=> Improve data validation

bin/train/main.py, nam/__init__.py, nam/train/gui.py
Resolves #105
Adds some hacky changes to `os` so that Ctrl+C causes the desired effect.
Has to be put in a few places, and since it needs to execute really early in the code, it's not really possible to put it in a single place and then re-use the code since that import might happen after the offending code locks in the wrong behavior.
See: https://stackoverflow.com/a/44822794
=> Fix graceful shutdowns for Lightning in Windows

bin/train/easy_colab.ipynb
This change adds a bit of explanation to the easy collab notebook about what the consequences are of changing the "architecture" parameter.
=> Add architecture information to easy collab

nam/train/core.py
Works on my M1 mac. I'd like to see some testing in the NAM facebook group to verify it still works on non-silicon machines.
I used the CPU environment yml to configure the environment for this.
=> Add Apple Metal support for faster training on M1/M2

nam/models/_exportable.py, nam/train/core.py, nam/train/gui.py
Add batch process functionality:
- simple approach to looping the train function over a number of files
- output audio field type updated to allow multiple file selection or single file (only a single input source can be used)
- 'modelname' added in some places to propagate the name of the final ".nam" file, so that multiple files can be dumped without overwriting each other.  Modelname is just the filename.
Add two new supporting options to GUI interface:
- automatically save plots to png next to model
- 'silent' run mode which will not prompt the user to close the delay window or final plot before finishing
https://user-images.githubusercontent.com/44332958/226157827-418f7ca3-f68d-4e10-a1c4-82323f168c4b.mp4
=> Batched training and silent

environment_cpu.yml, environment_gpu.yml, nam/models/base.py, nam/models/losses.py, requirements.txt, tests/test_nam/test_models/test_base.py
Fallback to `torch.device("cpu")` if calculation fails. If the device was already "cpu", pass out the exception raised.
Resolves #164
=> Run multi-resolution STFT loss on-device unless it fails

nam/models/_exportable.py
Remove indenting from the .nam files. Saves about 100kB per model (on the "standard" architecture)
Resolves #108
=> Smaller .nam files

nam/models/_base.py, nam/models/_exportable.py
Just a little quality-of-life change to move the "metadata" up before "weights" section of the exported .nam file. When manually inspecting the .nam file, it is nice to have all of the non-weight info at the top (previously, the "metadata" section was being written below the "weights").
=> Move "metadata" before "weights" in exported model

README.md, bin/train/easy_colab.ipynb, nam/train/core.py, nam/train/gui.py, setup.py
Only update metadata flag after batch is complete instead of every run so that all files in batch still have metadata
Before:
Every .nam after first file is missing user metadata because user can't open dialog mid-batch.
After:
All files in batch have the same user metadata.  New runs after the batch (or single file) are done still require opening the dialog.
=> Only update metadata flag after batch

nam/train/colab.py, nam/train/core.py
This PR adds support for LSTM training in the easy colab notebook.
@sdatkinson I know you want to keep the easy colab "easy", but I think this is a worthwhile change. It is very handy to be able to use the affordances of the easy colab for LSTM training.
Default behavior is unchanged, and the interface to the user is unchanged. I added a "model_type" parameter (defaults to "WaveNet"). If you set it to "LSTM", it will pick from LSTM architecture presets instead.
I added "standard", "lite", and "feather" configs for LSTM. These are somewhat arbitrary - any feedback is welcome.
=> Add LSTM to easy colab

nam/models/base.py
key for `mrstft_weight` under `parse_config` [was `mstft_weight`](https://github.com/sdatkinson/neural-amp-modeler/blob/b5568563c55d3e736c7e2a353214e32304068307/nam/models/base.py#L78).  Obviously a misspelling; make it right :)
=> Fix misspelled key for mrstft_weight

nam/train/colab.py, nam/train/core.py, nam/train/gui.py
Improves `v2_0_0.wav`-based training to be a little more permissive. Calibrated thresholds based on toy "noisy" data.
Adds the ability to ignore the checks on GUI & Colab if you think you know better 😉
=> Tweak v2_0_0.wav checks

environment_cpu.yml, environment_gpu.yml
tested with 
* Ubuntu 23.04
* Mac OS 13.3.1 on Apple Silicon M1
=> Restrict Python to 3.10 and earlier

README.md
Rename `"overdrive.wav"` to `"output.wav"`
Resolves #255
=> Rename demo output file from "overdrive.wav" to "output.wav"

nam/train/core.py
Just a small change to the checkpoint reporting to show 4 significant digits instead of 4 decimal places.
Models often train to ESRs lower than .0001, so it is useful to be able to see more digits.
=> Show 4 significant digits for checkpoint ESR

nam/train/core.py
Also skew the LSTM presets toward simpler architectures.
Based on my testing I think the set of LSTM presets is pretty good, but I'm happy to discuss alternatives. In my opinion, it really isn't worth going below 1x12, and if you go bigger than 1x24 you don't really have any advantage over WaveNet.
The proposed LSTM presets are:
"standard" - 1x24
"lite" - 2x8
"feather - 1x16
"nano" - 1x12
If you want to try these out, I've got a dev version of the "easy" colab here:
https://colab.research.google.com/github/mikeoliphant/neural-amp-modeler/blob/devel/bin/train/easy_colab.ipynb
Note that you need to add `model_type="LSTM"` to train LSTM presets.
=> Add "nano" preset for WaveNet and LSTM

bin/train/main.py, nam/data.py, nam/models/_base.py, nam/models/_exportable.py, nam/models/conv_net.py, nam/models/linear.py, nam/models/recurrent.py, nam/models/wavenet.py, nam/train/core.py, tests/test_nam/test_data.py
Resolves #281.
Models' export file now remembers what sample rate they were meant to be used at.
=> Log sample rate in `.nam` files

bin/train/easy_colab.ipynb
This PR just adds "nano" to the info section of the easy colab notebook.
=> Add "nano" info to easy colab

README.md
This updates the link to the easy colab to the latest version with the "nano" information.  @sdatkinson - I linked to that specific commit version, since that's what you had done previously.
=> Update link to easy colab

bin/train/main.py, nam/data.py, tests/test_nam/test_data.py, tests/test_nam/test_models/test_base.py
For the full CLI trainer only. Simplified trainers will continue to expect the reamp files provided.
Resolves #13
=> [FEATURE] Allow non-48k, non-24-bit training data

bin/train/main.py, nam/data.py, nam/models/_base.py, nam/models/base.py, tests/test_nam/test_models/test_base.py
Resolves #351.
Also adds functionality so that sample rate can be stored in plain state dicts via `net.state_dict()` (not used by the main trainer but maybe convenient).
Also makes snapshot models auto-export to `.nam`s at the end of `bin/train/main.py` 🙂
=> [BUGFIX] Store model's expected sample rate in Lightning checkpoints

bin/train/easy_colab.ipynb
This is the entire Colab notebook now: upload and one click.
Resolves #361
=> Simplify the Colab notebook and use GUI elements

nam/data.py, nam/models/_base.py, nam/models/conv_net.py, nam/train/core.py, tests/test_bin/test_train/test_main.py, tests/test_nam/test_data.py, tests/test_nam/test_train/test_core.py
=> [BREAKING] Get rid of `REQUIRED_RATE`

environment_gpu.yml, requirements.txt, setup.py
I didn't have a change to fully investigate, but this might do it.  Resolves this issue where code is updated to support pydantic 2 but old dependencies are not updated to match
=> [BUGFIX] Update Pydantic requirements

bin/train/easy_colab.ipynb
Auto (default):
Set manually (output lags input by 16 samples):
DAW over-compensated and the output happens 13 samples _before_ the input:
Resolves #390
=> [ENHANCEMENT] Put back manual reamp latency compensation in Colab

nam/train/_errors.py, nam/train/core.py, nam/train/gui.py
Pick a checkpoint...
And training will resume from it if possible.
If not possible, an error is communicated via a modal:
Also added functionality to disable the main window while one of the sub-windows (metadata, advanced options, this error modal) is open 😄 (see above)
I'm probably going to regret this one...I tried to anticipate the ways it might go wrong, but I'm going to bet against myself 😅 
Resolves #210
=> [FEATURE] GUI: Resume training from checkpoint

nam/models/_base.py
Closes #407 
This PR removes all uses of the deprecated `@abc.abstractproperty` decorator from the codebase. Replaced with `@property` and `@abc.abstractmethod`.
=> [chore] Replace deprecated uses of `@abc.abstractproperty`

nam/train/gui/__init__.py
Use justify instead of anchor to properly left align the text within the label
Before:
After:
=> [GUI] Left justify and prettify validation dialog

nam/models/losses.py, nam/models/metadata.py, nam/train/__init__.py, nam/train/_names.py, nam/train/colab.py, nam/train/gui/__init__.py, nam/train/gui/_resources/__init__.py, nam/train/gui/_resources/settings.py, nam/util.py
I don't use these. The convention in this repo is just the [PEP8 "leading underscore rule"](https://peps.python.org/pep-0008/).
=> Remove `__all__`s from package

nam_full_configs/data/single_pair.json, nam_full_configs/models/lstm.json, nam_full_configs/models/wavenet.json
* Stop using deprecated `"start"` and `"stop"` in favor of `"start_seconds"` and `"stop_seconds"`
* Formatter
* Improve LSTM configuration, bring to equivalent CPU w/ WaveNet
=> Update NAM-full configs

nam/train/_names.py, nam/train/core.py, tests/test_nam/test_train/test_core.py
Related to #442
We'll actually remove support in v0.11.
=> Deprecate non-v3.0.0 input signals

nam/train/core.py, tests/test_nam/test_train/test_core.py
Take the average of the responses to the latency impulses in order to denoise.
This fixes the errors in all 4 problematic files that I've gotten from users.
This could be even more solid if we had more impulses, but the two in the v3 input file is fine.
Resolves #389
=> [ENHANCEMENT] Better latency calculation via averaging

nam/train/core.py, tests/test_nam/test_train/test_core.py
added a test since its public now but that may be overkill
=> Make core get_callbacks public for extensions

nam/models/_base.py, nam/models/linear.py, tests/test_nam/test_models/_convolutional.py, tests/test_nam/test_models/test_conv_net.py, tests/test_nam/test_models/test_linear.py, tests/test_nam/test_models/test_wavenet.py
=> [BUGFIX] Workaround for PyTorch MPS bug with sequences longer than 65,536 samples

nam/models/base.py
=> Improve warning message when catching PyTorch MPS convolution bug

nam/models/conv_net.py, nam/models/exportable.py, nam/models/linear.py, nam/models/recurrent.py, nam/models/wavenet.py, tests/test_nam/test_models/test_base.py, tests/test_nam/test_models/test_exportable.py
This PR removes all occurrences of export_cpp_header across the codebase as it is no longer needed, addressing issue #536. The build and tests have been verified to pass successfully.
=> removed export_cpp_header in the whole of code

.github/workflows/python-package.yml, nam/train/_version.py, tests/test_nam/test_train/test_version.py
Get all of the tags from the commit history, enabling the package setup to guess the version satisfactorily.
Related: #544
=> [BUGFIX] Fix verison guessing in GitHub Actions

nam/models/_from_nam.py, nam/models/base.py, nam/models/losses.py, nam/train/colab.py, pyproject.toml, tests/_skips.py, tests/test_nam/test_models/test_from_nam.py, tests/test_nam/test_models/test_losses.py
Update auraloss to [my fork](https://github.com/Atkinson-Advanced-Modeling/auraloss/commit/4c45a90872ad047973c970bf6c70e7a52260e90c). Might try to PR upstream w/ fixes and get a v0.4.1 published on PyPI :)
This causes our use of the multi-resolution STFT loss, which doesn't use phase (since it's using the default parameters) to not have to call `torch.angle`, which is responsible for the exception that triggers the CPU fallback.
TLDR, Apple Silicon training is now faster!
Resolves #453 
Also contains some formatting fixes
=> [BUGFIX] Support MRSTFT on Apple Silicon

nam/_core.py, nam/data.py, nam/models/_from_nam.py, nam/train/core.py, tests/test_nam/test_models/test_from_nam.py
Little bugfix for backward compatibility to some old .nam files.
=> [BUGFIX] `nam.model.init_from_nam()`: Support files without `"sample_rate"` key.

docs/source/tutorials/colab.rst
Updated colab.rst by replacing the TODOs in the Training in the Cloud section with explanations for model parameters (epochs, architecture, latency_samples, ignore_checks, etc.).
=> Fill in model parameter details in Colab cloud training section
